// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"fiber-wire-template/internal/job"
	"fiber-wire-template/pkg/log"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewApp(logger *log.Logger) (*job.Job, error) {
	jobJob := job.NewJob(logger)
	return jobJob, nil
}

// wire.go:

var jobSet = wire.NewSet(job.NewJob)
