// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"fiber-wire-template/internal/command"
	"fiber-wire-template/internal/command/task"
	"fiber-wire-template/internal/repository"
	"fiber-wire-template/pkg/config"
	"fiber-wire-template/pkg/gredis"
	"fiber-wire-template/pkg/log"
	"fiber-wire-template/pkg/ozzodb"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewApp(logger *log.Logger, config2 *config.Config) (*command.Command, error) {
	db := ozzodb.NewDb(config2, logger)
	redis := gredis.NewRedis(config2)
	repositoryRepository := repository.NewRepository(db, redis, logger)
	demoTask := task.NewDemoTask(repositoryRepository)
	commandCommand := command.NewCommand(logger, demoTask)
	return commandCommand, nil
}

// wire.go:

var jobSet = wire.NewSet(command.NewCommand)

var RepositorySet = wire.NewSet(ozzodb.NewDb, gredis.NewRedis, repository.NewRepository)
